#!/bin/sh
set -e
if [ $# -lt 4 ]
then echo "Usage: $0 sc[N] [width] [height] [output file]" >&2
     exit 1
fi

prog=$1
xdim=$2
ydim=$3
output=$4

if [ $xdim -gt $ydim ]
then off=$(((xdim-ydim)/2))
     flags="-Dimgsize=$xdim -Dymin=$off -Dymax=$((xdim-off))"
else off=$(((ydim-xdim)/2))
     flags="-Dimgsize=$ydim -Dxmin=$off -Dxmax=$((ydim-off))"
fi

trap "rm -f sc-tmp.c sc-tmp" INT QUIT HUP TERM 0
m4 -Dprogress $flags -Dsubsamp=16 $prog.c.m4 > sc-tmp.c
cc -O3 sc-tmp.c -o sc-tmp
time ./sc-tmp | convert -depth 8 -comment "`cat LICENSE`" - $output
